version: 2

updates:
- package-ecosystem: mix
  directory: '/'
  schedule:
    interval: monthly
  groups:
    dev-dependencies:
      dependency-type: development
      update-types: ['minor', 'patch']
    prod-dependencies:
      dependency-type: production
      update-types: ['minor', 'patch']

- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: monthly
  groups:
    ci-actions:
      patterns: ['systemic-engineer/ci*']
    other-actions:
      patterns: ['*']
      exclude-patterns: ['systemic-engineer/ci*']
